AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  TableName:
    Type: String
    Default: 'MetaGame2'
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'

Resources:
  metagame2-inventory:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.inventory
      Runtime: nodejs10.x
      CodeUri: .
      Policies:
        - 
          DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName    
      Events:
        CreateAPI:
          Type: Api
          Properties:
            Path: /inventory
            Method: POST
        OtherOperationsAPI:
          Type: Api
          Properties:
            Path: /inventory/{user}
            Method: ANY
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - 
          AttributeName: user
          AttributeType: S
        - 
          AttributeName: inventory
          AttributeType: S  
      KeySchema:
        - 
          AttributeName: user
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

